### ISSUE TITLE
Please don’t do this

### ISSUE THREAD

**Issue by proteriax** [us/english-please#14]
Now that people [go around](https://github.com/alibaba/flutter-go/issues/343) and [demand translations](https://github.com/nondanee/UnblockNeteaseMusic/issues/182) for [repositories](https://github.com/tophubs/TopList/issues/23) that target an [exclusively Chinese audience](https://github.com/ThinkDevelopers/PHPConChina/issues/10), I think it’s very problematic that such a tool exists to *automatically* spam popular repos.

It’s fine if you are contributing to the repo by providing a translation, but it comes off as very condescending to use a copy-paste issue to demand people you don’t know, working on a project that you will probably never use to write a translation in your language. GitHub has an international audience and people should feel welcomed to have their repos exclusively in English or in their language of choice.

> Most people are disappointed when they see too many Chinese repos on Github trendings [sic]. There are only a limited number of trending repos and it is not possible to read close to half of them.

Apart from how problematic and offensive this sounds, no one should feel entitled to see only repos in their own language. If Chinese/French users have no problem with half of the repos _not in their language_, neither should you.

> This upsets most developers and ruins their habit of checking trending repos to discover more great open software.

Trending repositories are trending because of the very fact that *a lot of developers can read it*. If your experience is ruined by the mere presence of a foreign language, you probably have a bigger problem to deal with. If you are using Chrome, your translation is quite literally two clicks away (right click page and “translate into English”).

**Comment by us** [comment]
Yes sometimes can make mistakes, but it's just an offer, please don't forgot also my native language is not english, english is a global language. And I'm just offering you an offer.  

I know the translation, but it doesn't work exactly right, and and code are completely broken when comment lines are Chinese. Have you ever tried to translate a code for reading just comment lines, it's awful.

**Comment by proteriax** [comment]
It’s not an *offer* because you are not contributing anything. It’s a demand, and it’s incredibly disrespectful and against GitHub’s ToS to automatically submit issues to popular repos.

**Comment by us** [comment]
what is your suggestion to be more polite?

**Comment by clementhk** [comment]
It's probably better if you ask GitHub to tag repo's languages so we can all filter repo by languages. It is bad to auto spam repo, some would even consider it harassment.

**Comment by us** [comment]
Yes but it is definitely not my purpose. I just want to make the all information sharable. I don't want to filter languages because I don't want to miss the information in those repos. When I see a repo in Chinese I will open an issue and ask from them to translate to English so I just wanna make it automatic to save time.

**Comment by lizeyan** [comment]
@us 
It sounds like a threat that using a script to open issues automatically.
You should ask GitHub for language tags rather than ask other users offer you a English translation.
It is NOT their fault that their repos are on the trending list.
If your experience are ruined, go find GitHub, no the GitHub users. They are not employed by you or GitHub, and they are not responsible for your experience.
Most repos on GitHub are in English, but I have never seen Chinese/Japanese/Korean/French/German/Russian complain about it.
![image](https://user-images.githubusercontent.com/12494243/64692533-f970a400-d4c7-11e9-80fa-62946bc57dec.png)

**Comment by proteriax** [comment]
@us I recommend you to delete this repository.
